apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    app.kubernetes.io/name: MyApp
spec:
  containers:
  - name: nginx
    image: nginx:latest
    imagePullPolicy: Always
    ports:
    - containerPort: 80
    volumeMounts:
    - name: nginxvol
      mountPath: /usr/share/nginx/html/
  - image: busybox:1.28
    name: adapter
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo \\<h1\\>$(date)\\</h1\\> >> /html/index.html; sleep 5; done"]
    volumeMounts:
    - name: nginxvol
      mountPath: /html/
  initContainers:
  - name: init
    image: bitnami/git:latest
    command: ["bin/sh"]
    args: ["-c", "git clone https://github.com/gopichandnallani/webpage-test.git /html"]
    volumeMounts:
    - name: nginxvol
      mountPath: /html/
  volumes:
  - name: nginxvol
    emptyDir: {}