apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    env: prod
spec:
  containers:
  - name: nginx
    image: gopicn/rollingupdate:v1
    imagePullPolicy: Always
    ports:
    - containerPort: 80