apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myapp01
  name: myapp01
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp01
  template:
    metadata:
      labels:
        app: myapp01
    spec:
      containers:
      - image: gopicn/rollingupdate:v1
        name: rollingupdate

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: myapp01
  name: myapp01
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 80
  selector:
    app: myapp01